# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74ba439b4fafdf83bfd4d256f9430c4c3249af8fb57d96862386d4b77e6cd02b51299a41bc195f673e7fcacf2da39df264db4bed6acca04d3c1bd4f82d6999b
  admin_fb_id: 112151285836776
  fb_app_id: 179862209048045
  fb_app_secret: e09c5c82c9c676cf1b516d8c8cee0b83

test:
  secret_key_base: 9e0f858444c961889d9091532f56e543a52eb58f5f0c4aad359afdb47a74fb456ce3c5d6e0e54cb6eb2d1e77258623d2d8b8094cb4bc2ce2be801d3a74ae814f
  admin_fb_id: 112151285836776
  fb_app_id: 179862209048045
  fb_app_secret: e09c5c82c9c676cf1b516d8c8cee0b83

# Do not keep production secrets in the repository,
# instead read values from the environment.
#Add admin id, fb app id, secret id	
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_fb_id: <%= ENV["ADMIN_FB_ID"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
